import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FlyAir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" type="image/jpg" />
      </Head>

      <div className={styles.Navbar}>
        <div className={styles.logo}>
          <Image src="/logo.jpg" width={60} height={60} />
        </div>

        <div className={styles.searchs}>
          <input placeholder="Search" className={styles.inputtag} />
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="26"
            height="26"
            fill="currentColor"
            class="bi bi-search"
            viewBox="0 0 16 16"
          >
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
          </svg>
        </div>

        <div className={styles.links}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="30"
            fill="currentColor"
            class="bi bi-box-arrow-in-right"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"
            />
            <path
              fill-rule="evenodd"
              d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"
            />
          </svg>
          <Link href="/">
            <a>Login</a>
          </Link>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="30"
            fill="currentColor"
            class="bi bi-headset"
            viewBox="0 0 16 16"
          >
            <path d="M8 1a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a6 6 0 1 1 12 0v6a2.5 2.5 0 0 1-2.5 2.5H9.366a1 1 0 0 1-.866.5h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 .866.5H11.5A1.5 1.5 0 0 0 13 12h-1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h1V6a5 5 0 0 0-5-5z" />
          </svg>
          <Link href="#">
            <a>Contact</a>
          </Link>
        </div>
      </div>

      <div className={styles.mainimage}>
        <Image src="/backimg.jpg" height={550} width={1000} />
      </div>

      <h1 className={styles.heading}>Travel The World</h1>
      <h4 className={styles.heading}>
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry. Lorem Ipsum has been the industry's standard dummy text ever
        since the 1500s, when an unknown printer took a galley of type and
        scrambled it to make a type specimen book. It has survived not only five
        centuries, but also the leap into electronic typesetting, remaining
        essentially unchanged. It was popularised in the 1960s with the release
        of Letraset
      </h4>

      <h1 className={styles.heading}>Popular destinations</h1>
      <h4 className={styles.heading}>
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry. Lorem Ipsum has been the industry's standard dummy text ever
        since the 1500s, when an unknown printer took a galley of type and
        scrambled it to make a type specimen book. It has survived not only five
        centuries, but also the leap into electronic typesetting, remaining
        essentially unchanged. It was popularised in the 1960s with the release
        of Letraset
      </h4>

      <h2 className={styles.heading}>
        <li>Venice, Italy</li>
      </h2>
      <h2 className={styles.heading}>
        <li>Banff National Park, Canada</li>
      </h2>
      <h2 className={styles.heading}>
        <li>Great Ocean Road, Australia</li>
      </h2>
      <h2 className={styles.heading}>
        <li>Pitons, St Lucia</li>
      </h2>
      <h2 className={styles.heading}>
        <li>Tamil Nadu, India</li>
      </h2>

      <h1 className={styles.HeadingTwo}>Search Your Flights</h1>

      <div className={styles.Forms}>
        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>From</h4>
          <input
            placeholder="City Name or Country Name"
            className={styles.formInput}
          />
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>To</h4>
          <input
            placeholder="City Name or Country Name"
            className={styles.formInput}
          />
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>On Date</h4>
          <input placeholder="DD-MM-YYYY Format" className={styles.formInput} />
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>Price Between</h4>
          <div className={styles.Flexing}>
            <input type="checkbox" className={styles.CheckBox} />
            <h4 className={styles.budget}>20k to 50k</h4>
          </div>
          <div className={styles.Flexing}>
            <input type="checkbox" className={styles.CheckBox} />
            <h4 className={styles.budget}>50k to 100k</h4>
          </div>
          <div className={styles.Flexing}>
            <input type="checkbox" className={styles.CheckBox} />
            <h4 className={styles.budget}>100k to 150k</h4>
          </div>
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>Total Members</h4>
          <input
            placeholder="Total Members"
            type="number"
            className={styles.formInput}
          />
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>Total Adults</h4>
          <input
            placeholder="Total Adults"
            type="number"
            className={styles.formInput}
          />
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>Total Babies</h4>
          <input
            placeholder="Total Babies"
            type="number"
            className={styles.formInput}
          />
        </div>

        <div className={styles.flexinputs}>
          <h4 className={styles.Formheading}>Foods</h4>
          <div className={styles.Flexing}>
            <input type="checkbox" className={styles.CheckBox} />
            <h4 className={styles.budget}>Veg</h4>
          </div>
          <div className={styles.Flexing}>
            <input type="checkbox" className={styles.CheckBox} />
            <h4 className={styles.budget}>Non Veg</h4>
          </div>
          <div className={styles.Flexing}>
            <input type="checkbox" className={styles.CheckBox} />
            <h4 className={styles.budget}>Both</h4>
          </div>
        </div>

        <div>
          <button className={styles.buttons}>Search Flights</button>
        </div>
      </div>

      <div className={styles.footer}>
        <h5>2022 &copy; FlyAir| Inc.</h5>
      </div>
    </div>
  );
}
