import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FlyAir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" type="image/jpg" />
      </Head>

      <div className={styles.Navbar}>
        <div className={styles.logo}>
          <Image src="/logo.jpg" width={60} height={60} />
        </div>

        <div className={styles.searchs}>
          <input placeholder="Search" className={styles.inputtag} />
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="26"
            height="26"
            fill="currentColor"
            class="bi bi-search"
            viewBox="0 0 16 16"
          >
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
          </svg>
        </div>

        <div className={styles.links}>
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href="#">
            <a>Contact</a>
          </Link>
        </div>
      </div>
    </div>
  );
}
